flowchart TD
    examples__manifest["examples.manifest<br/>3 funcs"]
    project__map["project.map<br/>306 funcs"]
    swop__commands["swop.commands<br/>24 funcs"]
    swop__core["swop.core<br/>8 funcs"]
    swop__cqrs["swop.cqrs<br/>16 funcs"]
    swop__markpact["swop.markpact<br/>46 funcs"]
    swop__reconcile["swop.reconcile<br/>7 funcs"]
    swop__refactor["swop.refactor<br/>43 funcs"]
    swop__resolve["swop.resolve<br/>15 funcs"]
    swop__scan["swop.scan<br/>47 funcs"]
    swop__versioning["swop.versioning<br/>1 funcs"]
    swop__watch["swop.watch<br/>7 funcs"]
    swop__commands ==>|56| examples__manifest
    swop__commands ==>|25| project__map
    swop__reconcile ==>|7| examples__manifest
    swop__refactor ==>|4| project__map
    swop__watch ==>|4| project__map
    swop__core -->|2| examples__manifest
    swop__markpact -->|2| project__map
    swop__cqrs -->|2| project__map
    swop__versioning -->|1| examples__manifest
    swop__scan -->|1| project__map
    swop__watch -->|1| examples__manifest
    swop__resolve -->|1| project__map
