flowchart TD
    SUMD["SUMD<br/>21 funcs"]
    project__map["project.map<br/>21 funcs"]
    swop__cli["swop.cli<br/>8 funcs"]
    swop__core["swop.core<br/>8 funcs"]
    swop__export["swop.export<br/>4 funcs"]
    swop__introspect["swop.introspect<br/>6 funcs"]
    swop__reconcile["swop.reconcile<br/>7 funcs"]
    swop__refactor["swop.refactor<br/>32 funcs"]
    swop__sync["swop.sync<br/>3 funcs"]
    swop__utils["swop.utils<br/>3 funcs"]
    swop__versioning["swop.versioning<br/>1 funcs"]
