"""
swop init.

Scaffolds a ``swop.yaml`` at the project root, creates the ``.swop/``
state directory with a ``.gitignore`` guard, and appends swop-specific
entries to the repository ``.gitignore`` when missing.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable, List, Optional

from swop.config import DEFAULT_CONFIG_NAME, DEFAULT_STATE_DIR


DEFAULT_SWOP_YAML = """\
version: 1
project: {project}
language: python

# Directories that `swop scan` should walk for CQRS artifacts.
source_roots:
  - .

# Glob patterns that are always excluded from scanning.
exclude:
  - "**/tests/**"
  - "**/__pycache__/**"
  - "**/.venv/**"
  - "**/node_modules/**"

# Bounded contexts defined in this project.
# Each context maps a name to a source subtree.
bounded_contexts: []

# Message bus used by generated workers. Set `type: redis` to use Redis
# Streams instead of RabbitMQ.
# bus:
#   type: rabbitmq
#   url: "${{RABBITMQ_URL}}"

# Read-model database for projections.
# read_models:
#   engine: postgresql
#   url: "${{DB_URL}}"
"""


STATE_GITIGNORE = """\
# Generated by swop; do not edit by hand.
cache/
generated/
reports/
*.tmp
"""


GITIGNORE_ENTRIES = (
    "# swop",
    ".swop/",
    "swop-drift.log",
)


@dataclass
class InitResult:
    config_path: Path
    state_dir: Path
    created: List[Path] = field(default_factory=list)
    updated: List[Path] = field(default_factory=list)
    skipped: List[Path] = field(default_factory=list)

    def format(self) -> str:
        lines: List[str] = []
        for path in self.created:
            lines.append(f"  + {path}")
        for path in self.updated:
            lines.append(f"  ~ {path}")
        for path in self.skipped:
            lines.append(f"  = {path} (already up to date)")
        return "\n".join(lines) if lines else "nothing to do"


def init_project(
    root: Optional[Path] = None,
    *,
    project_name: Optional[str] = None,
    force: bool = False,
    update_gitignore: bool = True,
) -> InitResult:
    """Scaffold swop config + state dir in ``root``."""
    root = Path(root) if root else Path.cwd()
    root.mkdir(parents=True, exist_ok=True)

    name = project_name or root.name or "unnamed"
    config_path = root / DEFAULT_CONFIG_NAME
    state_dir = root / DEFAULT_STATE_DIR
    result = InitResult(config_path=config_path, state_dir=state_dir)

    # swop.yaml
    yaml_body = DEFAULT_SWOP_YAML.format(project=name)
    if not config_path.exists():
        config_path.write_text(yaml_body, encoding="utf-8")
        result.created.append(config_path)
    elif force:
        config_path.write_text(yaml_body, encoding="utf-8")
        result.updated.append(config_path)
    else:
        result.skipped.append(config_path)

    # .swop/ state dir
    if not state_dir.exists():
        state_dir.mkdir(parents=True, exist_ok=True)
        result.created.append(state_dir)

    state_gitignore = state_dir / ".gitignore"
    if not state_gitignore.exists():
        state_gitignore.write_text(STATE_GITIGNORE, encoding="utf-8")
        result.created.append(state_gitignore)
    else:
        result.skipped.append(state_gitignore)

    # ensure .swop/cache exists so incremental scans can write immediately
    cache_dir = state_dir / "cache"
    if not cache_dir.exists():
        cache_dir.mkdir(parents=True, exist_ok=True)
        result.created.append(cache_dir)

    # top-level .gitignore
    if update_gitignore:
        gitignore_path = root / ".gitignore"
        if _merge_gitignore(gitignore_path, GITIGNORE_ENTRIES):
            if gitignore_path in result.created or gitignore_path in result.updated:
                pass  # already listed
            elif gitignore_path.exists():
                result.updated.append(gitignore_path)
            else:
                result.created.append(gitignore_path)

    return result


def _merge_gitignore(path: Path, entries: Iterable[str]) -> bool:
    """Append missing entries to ``.gitignore``; return True on change."""
    existing = ""
    if path.exists():
        existing = path.read_text(encoding="utf-8")
    lines = existing.splitlines()
    existing_set = {line.strip() for line in lines if line.strip()}
    to_add = [entry for entry in entries if entry.strip() not in existing_set]
    if not to_add:
        return False
    prefix = existing
    if prefix and not prefix.endswith("\n"):
        prefix += "\n"
    new_body = prefix + "\n".join(to_add) + "\n"
    path.write_text(new_body, encoding="utf-8")
    return True
