"""Generate registry.json + REGISTRY.md from validated Contracts."""
from __future__ import annotations
import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List
from swop.registry.loader import Contract

@dataclass
class RegistryGenerationResult:
    json_path: Path
    md_path: Path
    command_count: int = 0
    query_count: int = 0
    event_count: int = 0
    module_count: int = 0
    def format(self) -> str:
        return (f"[REGISTRY] {self.json_path.name}+{self.md_path.name} cmd={self.command_count} qry={self.query_count} evt={self.event_count} mods={self.module_count}")

def _ep(http: Any) -> str:
    return http.get("endpoint","—") if isinstance(http,dict) else str(http or "—")
def _ch(ws: Any) -> str:
    return ws.get("channel","—") if isinstance(ws,dict) else str(ws or "—")

def generate_registry_json(contracts: List[Contract]) -> Dict[str,Any]:
    reg: Dict[str,Any] = {"_generated": datetime.now(timezone.utc).isoformat(),"_total": len(contracts),"commands":{},"queries":{},"events":{}}
    for c in contracts:
        e = {"file": c.path.name,"kind": c.kind,"version": c.raw.get("version","?"),"module": c.raw.get("module","—"),"description": c.raw.get("description","")}
        t = c.raw.get("transport",{})
        if isinstance(t,dict):
            e["transport"] = {"http": _ep(t.get("http",{})),"ws": _ch(t.get("ws",{}))}
        if isinstance(c.raw.get("layers"),dict):
            e["layers"] = c.raw["layers"]
        if "command" in c.raw:
            e["events"] = c.raw.get("events",{}); reg["commands"][c.name] = e
        elif "query" in c.raw:
            reg["queries"][c.name] = e
        elif "event" in c.raw:
            e["producers"] = c.raw.get("producers",{}); e["consumers"] = c.raw.get("consumers",[])
            reg["events"][c.name] = e
    return reg

def generate_registry_md(contracts: List[Contract]) -> str:
    cmds = [c for c in contracts if "command" in c.raw]
    qrys = [c for c in contracts if "query" in c.raw]
    evts = [c for c in contracts if "event" in c.raw]
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = ["# Contract Registry","",f"> Auto-generated by swop — {now}  ",f"> Total: **{len(contracts)}** (commands={len(cmds)}, queries={len(qrys)}, events={len(evts)})  ","> Source: `contracts/*.{command,query,event}.json`","","---",""]
    lines += ["## Command Map","","| Command | Module | HTTP | WS | Python Layer | Events |","|---------|--------|------|----|-------------|--------|"]
    for c in cmds:
        l=c.raw.get("layers",{}); lines.append(f"| `{c.name}` | `{c.raw.get('module','—')}` | `{_ep(c.raw.get('transport',{}).get('http',{}))}` | `{_ch(c.raw.get('transport',{}).get('ws',{}))}` | `{l.get('python','—')}` | {', '.join(c.raw.get('events',{}).values()) or '—'} |")
    lines += ["","## Query Map","","| Query | Module | HTTP | WS | Python Layer |","|-------|--------|------|----|-------------|"]
    for c in qrys:
        l=c.raw.get("layers",{}); lines.append(f"| `{c.name}` | `{c.raw.get('module','—')}` | `{_ep(c.raw.get('transport',{}).get('http',{}))}` | `{_ch(c.raw.get('transport',{}).get('ws',{}))}` | `{l.get('python','—')}` |")
    lines += ["","## Event Map","","| Event | Kind | Module | Producer | Consumers |","|------|------|--------|----------|-----------|"]
    for c in evts:
        p=c.raw.get("producers",{}); prod=p.get("python","—") if isinstance(p,dict) else "—"
        cons=c.raw.get("consumers",[]); cs=", ".join(cons) if isinstance(cons,list) else str(cons)
        lines.append(f"| `{c.name}` | `{c.kind}` | `{c.raw.get('module','—')}` | `{prod}` | {cs or '—'} |")
    for title,items,key1,key2 in (("Command",cmds,"input","output"),("Query",qrys,"input","output"),("Event",evts,"payload","")):
        lines += ["","---","",f"## {title} Details",""]
        for c in items:
            lines += [f"### `{c.name}`","",f"**Kind**: `{c.kind}` | **Module**: `{c.raw.get('module','—')}` | **Version**: `{c.raw.get('version','?')}`  ",f"**Description**: {c.raw.get('description','—')}","",f"**{key1.capitalize()}:**","","| Field | Type | Required | Description |","|-------|------|----------|-------------|"]
            for fn,meta in c.raw.get(key1,{}).items():
                m=meta if isinstance(meta,dict) else {}; req="✅" if m.get("required") else "—"; desc=m.get("description","")
                lines.append(f"| `{fn}` | `{m.get('type','?')}` | {req} | {desc} |")
            if key2:
                lines += ["",f"**{key2.capitalize()}:**","","| Field | Type |","|-------|------|"]
                for fn,meta in c.raw.get(key2,{}).items():
                    m=meta if isinstance(meta,dict) else {}; lines.append(f"| `{fn}` | `{m.get('type','?')}` |")
            if "storage" in c.raw:
                s=c.raw["storage"]; lines.append(f"**Storage**: `{s.get('database')}` → table `{s.get('table')}`")
            if "layers" in c.raw and c.raw["layers"]:
                lines += ["","**Layers:**",""]
                for k,v in c.raw["layers"].items():
                    lines.append(f"- **{k}**: `{v}`")
            if "events" in c.raw and c.raw["events"]:
                lines += ["","**Events:**",""]
                for k,v in c.raw["events"].items():
                    lines.append(f"- `{k}`: `{v}`")
            if "producers" in c.raw and c.raw["producers"]:
                lines += ["","**Producers:**",""]
                for k,v in c.raw["producers"].items():
                    lines.append(f"- `{k}`: `{v}`")
            lines += ["","---",""]
    return "\n".join(lines)

def write_registry(contracts_dir: Path, contracts: List[Contract]) -> RegistryGenerationResult:
    reg = generate_registry_json(contracts)
    json_path = contracts_dir / "registry.json"
    md_path = contracts_dir / "REGISTRY.md"
    json_path.write_text(json.dumps(reg, indent=2, ensure_ascii=False), encoding="utf-8")
    md_path.write_text(generate_registry_md(contracts), encoding="utf-8")
    modules = {c.raw.get("module","") for c in contracts}
    return RegistryGenerationResult(json_path=json_path, md_path=md_path,
        command_count=len(reg.get("commands",{})),
        query_count=len(reg.get("queries",{})),
        event_count=len(reg.get("events",{})),
        module_count=len(modules - {''}))
